[package]
name = "ronin"
version = "0.1.0"
edition = "2021"
description = "A fast Ninja-compatible build tool implemented in Rust"
license-file = "LICENSE"

[lib]
path = "src/lib.rs"

[dependencies]
bstr = { version = "1", default-features = false, features = ["std"] }

[profile.release]
lto = "fat"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
redundant_pub_crate = "allow"
undocumented_unsafe_blocks = "deny"
