use crate::deps::{depsentry, depsnodes, visit_dependencies, DepsLog};
use crate::error::{ToolError, ToolOperation};
use crate::graph::{nodeget, Graph, NodeId};
use crate::missing_deps::MissingDependencyScanner;
use crate::os::RealDiskInterface;
use crate::util::{BString, ByteSlice};
use std::fmt::Write;

pub(crate) fn deps(graph: &Graph, log: &DepsLog, targets: &[BString]) -> Result<String, ToolError> {
    let nodes = if targets.is_empty() {
        depsnodes(log).collect::<Vec<_>>()
    } else {
        targets
            .iter()
            .map(|target| {
                nodeget(graph, target.as_bytes()).ok_or_else(|| ToolError::UnknownTarget {
                    path: target.clone(),
                })
            })
            .collect::<Result<Vec<_>, _>>()?
    };
    let disk = RealDiskInterface;
    let mut output = String::new();
    for node in nodes {
        let path = &graph.node(node).path;
        let Some(entry) = depsentry(log, node) else {
            let _ = writeln!(output, "{path}: deps not found");
            continue;
        };
        let mtime = disk
            .stat(path.to_path().expect("byte paths are valid on Unix"))
            .map_err(|source| ToolError::io(ToolOperation::Stat, Some(path.clone()), source))?;
        let state = if mtime == 0 || mtime > entry.mtime {
            "STALE"
        } else {
            "VALID"
        };
        let _ = writeln!(
            output,
            "{path}: #deps {}, deps mtime {} ({state})",
            entry.deps.nodes.len(),
            entry.mtime
        );
        for dependency in &entry.deps.nodes {
            let _ = writeln!(output, "    {}", graph.node(*dependency).path);
        }
        output.push('\n');
    }
    Ok(output)
}

pub(crate) fn missing_deps(graph: &Graph, log: &DepsLog, targets: &[NodeId]) -> (String, i32) {
    let mut scanner = MissingDependencyScanner::default();
    visit_dependencies(log, |node, dependency| {
        scanner.record_dependency(node, dependency);
    });
    for target in targets {
        scanner.process_node(graph, *target);
    }
    let mut output = String::new();
    for report in scanner.reports() {
        let _ = writeln!(
            output,
            "Missing dep: {} uses {} (generated by {})",
            report.consumer, report.generated, report.generator_rule
        );
    }
    let _ = writeln!(output, "Processed {} nodes.", scanner.processed_nodes());
    if scanner.had_missing_dependencies() {
        let _ = writeln!(
            output,
            "Error: There are {} missing dependency paths.",
            scanner.missing_dependency_paths()
        );
        let _ = writeln!(
            output,
            "{} targets had depfile dependencies on {} distinct generated inputs (from {} rules) without a non-depfile dep path to the generator.",
            scanner.nodes_missing_dependencies(),
            scanner.generated_nodes(),
            scanner.generator_rules()
        );
        output.push_str(
            "There might be build flakiness if any of the targets listed above are built alone, or not late enough, in a clean output directory.\n",
        );
        (output, 3)
    } else {
        output.push_str("No missing dependencies on generated files found.\n");
        (output, 0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::deps as deps_module;
    use crate::graph::nodeget;
    use crate::tool::test_support::Fixture;

    #[test]
    fn reports_empty_dependency_state_and_a_clean_missing_deps_scan() {
        let mut fixture = Fixture::parse(
            "state",
            concat!(
                "rule cat\n",
                "  command = cat $in > $out\n",
                "build output: cat source\n",
                "build all: phony output\n"
            ),
        );
        let path = fixture.directory.join(".ninja_deps");
        let (log, warning) = deps_module::depsloadlog(&path, &mut fixture.graph).unwrap();
        assert!(warning.is_none());
        assert_eq!(deps(&fixture.graph, &log, &[]).unwrap(), "");

        let all = nodeget(&fixture.graph, b"all").unwrap();
        let (output, exit_code) = missing_deps(&fixture.graph, &log, &[all]);
        assert_eq!(exit_code, 0);
        assert!(output.starts_with("Processed "));
        assert!(output.ends_with("No missing dependencies on generated files found.\n"));
    }
}
