#!/bin/sh
# Run GNU Make's own test suite as discovery input for Ronin's Make compiler.
#
# This is broad, independently-authored input. The vendored corpus under
# kati/testcase was written by kati's authors to describe kati, so it can only
# ever say how well Ronin matches what kati already did. This suite was written
# by GNU Make's authors to describe GNU Make, and nobody involved in it has
# heard of us. Its exact-output pass rate is not a compatibility score: GNU
# Make's runner is not the product Ronin is implementing.
#
# The suite is GPLv3 and is not vendored. `reference/gnumake` is a pinned
# checkout, gitignored, fetched with:
#
#   git clone https://git.savannah.gnu.org/git/make.git reference/gnumake
#
# It is a Perl driver that eval's each script in tests/scripts, writes a
# makefile, runs the program, and compares captured stdout+stderr as an exact
# string. Before any of that it interrogates the program six times and
# configures the run from the answers — see set_more_defaults. The fourth of
# those probes is how it learns what to call us: it matches the empty-makefile
# diagnostic against /(.*): \*\*\* No targets\.  Stop\./ and writes the capture
# into every expected diagnostic as #MAKE#. That is the suite offering to
# measure a differently-named make under its own name, and it is why Ronin
# answers with `ronin:` rather than claiming to be Make.
#
# Two accommodations, both of which are the harness's problem rather than
# Ronin's:
#
#   The driver and failed builds leave outputs beside tests/. Reusing that
#   directory makes a later run observe targets from an earlier one, so the
#   pinned checkout is only the source for a disposable detached worktree.
#
#   config-flags.pm is generated by GNU Make's own configure. A checkout that
#   has not been built does not have one, and the driver dies without it.
#
#   The driver opens a great many descriptors at once. The default soft limit
#   on this host lets it exhaust them, and real GNU Make fails a test for the
#   same reason, so the limit is lowered to where both tools agree.
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo_root"

source_suite=$repo_root/reference/gnumake
expected_suite=d66a65ad5a0e31b287f53930b0f09e31801f1613
if [ ! -d "$source_suite/tests/scripts" ]; then
    echo "check-make-upstream: no suite at $source_suite." >&2
    echo "Clone it: git clone https://git.savannah.gnu.org/git/make.git \\" >&2
    echo "    reference/gnumake" >&2
    echo "It is GPLv3 and deliberately not vendored." >&2
    exit 1
fi
actual_suite=$(git -C "$source_suite" rev-parse HEAD)
if [ "$actual_suite" != "$expected_suite" ]; then
    echo "check-make-upstream: expected GNU Make 4.4.1 at $expected_suite," >&2
    echo "but reference/gnumake is at $actual_suite." >&2
    exit 1
fi

cargo build --release --bin ronin
cargo build --release --example make_upstream

mkdir -p "$repo_root/target"
scratch=$(mktemp -d "$repo_root/target/make-upstream.XXXXXX")
case "$scratch" in
    "$repo_root"/target/make-upstream.*) ;;
    *)
        echo "check-make-upstream: unsafe scratch directory $scratch" >&2
        exit 1
        ;;
esac
suite=$scratch/gnumake

cleanup() {
    status=$?
    trap - EXIT HUP INT TERM
    set +e
    if [ -d "$suite" ]; then
        git -C "$source_suite" worktree remove --force "$suite" >/dev/null 2>&1
    fi
    rm -rf "$scratch"
    git -C "$source_suite" worktree prune >/dev/null 2>&1
    exit "$status"
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

git -C "$source_suite" worktree add --detach "$suite" "$expected_suite"

# Make mode is reached by the invoked name and by nothing else, so pointing the
# suite at Ronin means a make-named link rather than a flag.
#
# Inside this run's scratch directory rather than at a shared path. Concurrent
# runs must not replace one another's make-named link.
bin=$scratch/bin
mkdir -p "$bin"
ln -s "$repo_root/target/release/ronin" "$bin/make"

cat > "$suite/tests/config-flags.pm" <<'PM'
# Written by check-make-upstream.sh: GNU Make's configure generates this and a
# source-only checkout has none, but nothing here is measured.
%CONFIG_FLAGS = (AM_LDFLAGS => '', AM_CFLAGS => '', CC => 'cc', CFLAGS => '',
                 CPP => 'cc -E', CPPFLAGS => '', GUILE => 'n', LDFLAGS => '',
                 USE_SYSTEM_GLOB => 'n');
1;
PM

ulimit -n 512 || true

# Two programs run here and they take different flags, so `--update` is taken
# for the classifier before anything else is passed to the driver. It is worth
# the special case: the driver does not reject an argument it has never heard
# of, it reads it as a category name and runs nothing, and a run that tested
# nothing still leaves a work directory the classifier will happily read.
update=
if [ "${1:-}" = "--update" ]; then
    update=--update
    shift
fi

(
    cd "$suite/tests"
    # The driver's exit status counts failures, and its own summary is not the
    # result: Ronin narrates a build the way Ninja does and is not trying to
    # produce GNU Make's output. The classifier below turns the raw output into
    # a discovery inventory rather than treating the driver's count as a gate.
    perl ./run_make_tests.pl -make "$bin/make" "$@" || true
)

# The classifier inventories compiler-shaped candidates, interface
# observations, narration, and residue that still needs a focused reproducer.
# Inventory drift fails for review; none of these exact runner-output classes is
# itself the build-intent conformance gate.
classifier_status=0
"$repo_root/target/release/examples/make_upstream" \
    --work "$suite/tests/work" \
    --inventory "$repo_root/tests/make_upstream_inventory.tsv" \
    $update || classifier_status=$?
exit "$classifier_status"
