#!/bin/sh
# Run GNU Make's own test suite against Ronin's Make mode.
#
# This is the unbiased measure. The vendored corpus under kati/testcase was
# written by kati's authors to describe kati, so it can only ever say how well
# Ronin matches what kati already did. This suite was written by GNU Make's
# authors to describe GNU Make, and nobody involved in it has heard of us.
#
# The suite is GPLv3 and is not vendored. `reference/gnumake` is a pinned
# checkout, gitignored, fetched with:
#
#   git clone https://git.savannah.gnu.org/git/make.git reference/gnumake
#
# It is a Perl driver that eval's each script in tests/scripts, writes a
# makefile, runs the program, and compares captured stdout+stderr as an exact
# string. Before any of that it interrogates the program six times and
# configures the run from the answers — see set_more_defaults. The fourth of
# those probes is how it learns what to call us: it matches the empty-makefile
# diagnostic against /(.*): \*\*\* No targets\.  Stop\./ and writes the capture
# into every expected diagnostic as #MAKE#. That is the suite offering to
# measure a differently-named make under its own name, and it is why Ronin
# answers with `ronin:` rather than claiming to be Make.
#
# Two accommodations, both of which are the harness's problem rather than
# Ronin's:
#
#   config-flags.pm is generated by GNU Make's own configure. A checkout that
#   has not been built does not have one, and the driver dies without it.
#
#   The driver opens a great many descriptors at once. The default soft limit
#   on this host lets it exhaust them, and real GNU Make fails a test for the
#   same reason, so the limit is lowered to where both tools agree.
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo_root"

suite=$repo_root/reference/gnumake
if [ ! -d "$suite/tests/scripts" ]; then
    echo "check-make-upstream: no suite at $suite." >&2
    echo "Clone it: git clone https://git.savannah.gnu.org/git/make.git \\" >&2
    echo "    reference/gnumake" >&2
    echo "It is GPLv3 and deliberately not vendored." >&2
    exit 1
fi

cargo build --release --bin ronin

# Make mode is reached by the invoked name and by nothing else, so pointing the
# suite at Ronin means a make-named link rather than a flag.
bin=${TMPDIR:-/tmp}/ronin-make-upstream/bin
rm -rf "$bin"
mkdir -p "$bin"
ln -s "$repo_root/target/release/ronin" "$bin/make"

if [ ! -f "$suite/tests/config-flags.pm" ]; then
    cat > "$suite/tests/config-flags.pm" <<'PM'
# Written by check-make-upstream.sh: GNU Make's configure generates this and a
# source-only checkout has none, but nothing here is measured.
%CONFIG_FLAGS = (AM_LDFLAGS => '', AM_CFLAGS => '', CC => 'cc', CFLAGS => '',
                 CPP => 'cc -E', CPPFLAGS => '', GUILE => 'n', LDFLAGS => '',
                 USE_SYSTEM_GLOB => 'n');
1;
PM
fi

ulimit -n 512 || true

cd "$suite/tests"
# The driver's exit status counts failures, and every failure here is expected
# until Make mode is finished; the summary it prints is the result.
perl ./run_make_tests.pl -make "$bin/make" "$@" || true
